# Github actions to test on push and and pull requests and send notification to slack

name: Deploy to Production
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_python_add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest ./

      - name: Notify Slack  
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: |
            *Deployment Status:* `${{ job.status }}`
            *Branch:* `${{ github.ref }}`
            *Commit:* `${{ github.sha }}`